### ISSUE TITLE
ESLintのエラーチェック対象の調査

### ISSUE THREAD

**Issue by takasaki376** [takasaki376/qastclone#4]
基本的にQinMemoでチェックされている内容を採用しようとしています。
理由は、今後Qinのプロダクト開発に携わった際に、エラーが発生しないようにするためです。
Next.jsの方のリポジトリでISSUEを作成しましたが、React版にも同様のエラーチェックを行う予定です。

[QinMemoでのESLintの設定](https://github.com/qin-salon/qin-memo/blob/96efe5ee1a7c89cd35caeaefd65bbd0cb103b8a5/.eslintrc.js#L17)です。

環境構築が思ったより早く進むので、チェック内容の調査を手伝ってもらえないでしょうか。
こちらはプルリクを投げるのではなく、ISSUEに対して返信をお願いします。

私も調べた際は、返信で記載します。

ESLintの事を調査する上で参考になったサイト
[煩雑になりがちな ESLint の設定方法まとめ、 2020 年版](https://dev.classmethod.jp/articles/eslint-configurations-2020/)
[ESLint 設定を作成する技術 2021年版](https://zenn.dev/januswel/articles/402774d76424e71ac906)

**Comment by mike3104** [comment]
root: true
⇨このeslintrc.jsがrootであることを示すために記載。他のフォルダ内のeslintrc.jsを参照にしないようになる。

**Comment by takasaki376** [comment]
no-default-export : "error"
default export を使用禁止にしてnamed exportのみ利用可能にする。
[なぜ default export を使うべきではないのか？](https://engineering.linecorp.com/ja/blog/you-dont-need-default-export/)

**Comment by takasaki376** [comment]
@typescript-eslint/naming-convention
変数名や関数名のルールを定義できる。
QinMemoにはないけど、追加した方が統一できて良さそう。
ルールは詳細に定義できるため、追加する場合は要検討。

[公式ページ](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md)
[日本語の紹介記事](https://dev.classmethod.jp/articles/shuntaka9576-check-eslint/)

**Comment by takasaki376** [comment]
直接ESlintのルールではありませんが、ESlintでエラーになっている場合は、git commit時にエラーにする方法
https://kic-yuuki.hatenablog.com/entry/2019/05/27/090515

最新バージョンでの設定方法
https://qiita.com/sprout2000/items/29e8a637dda259bab26d

しまぶーさんも、QinMemoに追加するか検討中とのことです。

**Comment by yoko-at-home** [comment]
対象ルール調査結果ですが、[Excel](’https://1drv.ms/x/s!AoZxNvLj1__qhBDUWZe-RzJyGRZt’)にしました。編集権限をつけていますので、間違っている場合は、上書きして、コメント者の名前を上書きいただければと思います。

**Comment by takasaki376** [comment]
QinMemoの設定対象は網羅できたようなので、調査は完了にします。
ライブラリのインストールなど、設定時の手順などをまとめる際に、当ISSUEでの返信を使うようにします。
ESlintの設定完了時の当ISSUEはCloseにします。

**Comment by takasaki376** [comment]
## ライブラリインストール
`yarn add -D eslint-plugin-react`

## 初期設定
{
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,     ---指定方法は別途調査
    sourceType: "module",
  },
  settings: {
    react: {
      version: "detect",
    },
  },
  "plugins": ["react"],
}

## よく使うルールの一括適用
typescriptを導入する場合は、typescriptの後に記載すること
{
  "extends": [
       "plugin:react/recommended",
  ],
}

## ルール設定
"react/react-in-jsx-scope": "off",
"react/display-name": "error",
※みけさんが調査済のため、説明は省略

**Comment by takasaki376** [comment]
## ライブラリインストール
`yarn add -D eslint-plugin-react-hooks`

## 初期設定
{
  "plugins": ["react-hooks"],
}

## よく使うルールの一括適用
QinMemoでは使っていないし、今回は指定しない見込み
```
{
  "extends": [
    "plugin:react-hooks/recommended"
  ]
}
```

## ルール設定
```
"rules": {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
}
```
※みけさん、yokoさんが調査済のため、説明は省略

**Comment by takasaki376** [comment]
## ライブラリのインストール
`yarn add -D eslint-plugin-simple-import-sort`

## 初期設定
```
{
  "plugins": ["simple-import-sort"]
}
```

## ルール設定
```
{
  "rules": {
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error"
  }
}
```
yokoさんが調査済のため、説明は省略

**Comment by takasaki376** [comment]
## ライブラリのインストール
`yarn add -D eslint-plugin-jsx-a11y`

## 初期設定
{
  "plugins": [
    "jsx-a11y"
  ]
}

## よく使うルールの一括適用
```
{
  "extends": [
    "plugin:jsx-a11y/recommended"
  ]
}
```
## ルール設定
```
{
  "rules": {
    "jsx-a11y/anchor-is-valid": [
      "error",
      { components: ["Link"], specialLink: ["hrefLeft", "hrefRight"], aspects: ["invalidHref", "preferButton"] },
    ],
  }
}
```
yokoさんが調査済のため、説明は省略
